version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  commands:
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - pip install jax-xc
    - cd docs && make html
    - mkdir -p _readthedocs
    - ln -s docs/_build/html _readthedocs/html
