# Copyright 2022 Garena Online Private Limited
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

exports_files([
    "wrap.py",
    "wrap.cc.jinja",
    "so_naming.patch",
    "windows.patch",
    "register.cc",
    "register.h",
    "libxc.cc",
    "build.jinja",
    "gen_build.py",
])
